### ISSUE TITLE
white box for cursor

### ISSUE THREAD

**Issue by CODGOD19** [TheDeadSnake/LC-Touchscreen#1]
cursor to interact is big white box how to fix?

**Comment by TheDeadSnake** [comment]
If you are still on version 1.0.0 just updating the plugin should be enough as the ressource path was wrong in the first version. 
If the update does not help, check if inside the "\<ThunderStoreFolder\>\DataFolder\LethalCompany\profiles\Default\BepInEx\plugins\TheDeadSnake-Touchscreen" folder there is a "HoverIcon.png" file. If it does not exist you can either download it [here](https://github.com/TheDeadSnake/LC-Touchscreen/blob/master/images/HoverIcon.png) or create your own 186x186 png file.

**Comment by TheDeadSnake** [comment]
I will close the issue for now, should the issue remain or another issue pop up please contact me again.
