### ISSUE TITLE
[Suggestion] Using boosters that's being held by players

### ISSUE THREAD

**Issue by GliitchedEntity** [TheDeadSnake/LC-Touchscreen#10]
As for now, there is no way to interact with a radar booster on touchscreen if it's held by a player.
Having such ability would be a great addition.

**Comment by TheDeadSnake** [comment]
Sorry for the late reply but I had no time to update the plugin over Christmas. It's a good suggestion I will implement it in v1.0.7, however I will first have to check if you can flash a radar a player is holding as that would be a bit odd with the current keybind layout.

**Comment by TheDeadSnake** [comment]
From v1.0.7 Radar boosters held by players will now get priority over switch camera key bind
