### ISSUE TITLE
[Duplicate] Pointer İssues

### ISSUE THREAD

**Issue by theoxygenn** [TheDeadSnake/LC-Touchscreen#11]
![Ekran görüntüsü 2023-12-23 025015](https://github.com/TheDeadSnake/LC-Touchscreen/assets/100039420/6ee32ab3-33de-427e-bc60-53f21fba835c)

can u help me for this

**Comment by TheDeadSnake** [comment]
Please refer to the [Wiki](https://github.com/TheDeadSnake/LC-Touchscreen/wiki/Known-issues) or issues #6, #1.
Alternatively from version 1.0.4+ you can change the pointer icon path in the config file (Either relative to the plugin folder or a full system path).
