### ISSUE TITLE
it's not working with other moons mods

### ISSUE THREAD

**Issue by drink1101** [TheDeadSnake/LC-Touchscreen#13]
in the original moons its still working but in those mods' moon it don't work. 
![sp20231229_043423_332](https://github.com/TheDeadSnake/LC-Touchscreen/assets/85337928/c8cf4d12-49ea-4271-9e2a-1ee828018ed8) this pic im in march still working.

![sp20231229_043633_435](https://github.com/TheDeadSnake/LC-Touchscreen/assets/85337928/186a0345-a9a5-453d-a583-0eefa35faabd)
![sp20231229_043646_967](https://github.com/TheDeadSnake/LC-Touchscreen/assets/85337928/d310cbc5-e73f-4441-b9fa-61cef42bacde)

**Comment by TheDeadSnake** [comment]
The issue most likely stems from the level loading "detection", I will take a look at it tomorrow.
https://github.com/TheDeadSnake/LC-Touchscreen/blob/54dd4f94934fe6d5c98ef1b1f0888a25c8dbe0dc/Plugin.cs#L47C90-L47C90

**Comment by TheDeadSnake** [comment]
Fixed in v1.0.8
