### ISSUE TITLE
Config file is not generated

### ISSUE THREAD

**Issue by renatamer** [TheDeadSnake/LC-Touchscreen#14]
Changing the keybindings does not seem possible.

**Comment by TheDeadSnake** [comment]
The configuration file can be found inside the config folder of BepInEx and is called "me.pm.TheDeadSnake.cfg".

If you use the Thunderstore Mod Manager you can also go to the Tab "Edit config" scroll down to "BepInEx/config/me.pm.TheDeadSnake.cfg" and click on "Edit Config" or "Open File".

**Comment by renatamer** [comment]
Thank you very much, I was able to find it under the given name.
