### ISSUE TITLE
A way to disable the PointerIcon completely

### ISSUE THREAD

**Issue by PickeBlind** [TheDeadSnake/LC-Touchscreen#17]
Hello, I apologize if I missed something, but is there a way to disable the PointerIcon completely? I tried leaving it empty but it defaults to the HoverIcon. (I'm using the Crosshair mod, and two crosshairs make it kind of weird.)

I thought of making a transparent icon, but that seems more like a workaround, and my friends would have to do it too

**Comment by TheDeadSnake** [comment]
No, currently you can only disable the tool tips but not the pointer itself. As you already mentioned the quick fix would be to use a transparent image. 
I'll implement a clearer way in v1.0.9, however as I mentioned in the other open issue already, I currently do not have the time to do it so it may take a bit before a update will be released.

**Comment by PickeBlind** [comment]
Alright, thank you for the quick answer!

**Comment by TheDeadSnake** [comment]
Added in v1.0.9
