### ISSUE TITLE
[Compatibility Request] Zoomed out map Functionality

### ISSUE THREAD

**Issue by CommanderSlav** [TheDeadSnake/LC-Touchscreen#19]
The mod still functions as it should to a degree, but when this mod is paired with Enhanced Radarbooster and the zoom is set at 2x - It seems that it still wants to function as if it's at "normal view" or 1x - As in, anything outside this "normal viewing" can't be used. 

For example, if you follow a player, this would be a normal POV, if you see doors, mines, etc. You can click on them to disable them. Still, if you're watching a radar booster and the map is zoomed out, if anything that is shown is "too far" (despite being viewable), you cannot interact with these things unless it's within the "normal view" radius.

It's fairly simple to get an idea of what I mean by having both your mod and EnhancedRadarBooster and having a teammate inside and having any sort of object on the outer areas of the screen, you'll notice you cannot interact with them because I presume the mod is stuck thinking that those areas are actually "out of bounds" when the screen POV is zoomed out.

**Comment by TheDeadSnake** [comment]
I've installed the mod, hosted a lobby and placed a Radar Booster inside the Facility and everything works as expected, i.e. Everything (Turret, Mines, Doors) that the Monitor is showing is clickable even if it's outside the default view range.
This might only occur when joining someones lobby.
![OOR](https://github.com/TheDeadSnake/LC-Touchscreen/assets/60078424/96bed8f4-ab61-4042-bbc4-ebfea7724717)

Based on the current information this might be an issue with some kind of anti-cheat meassure.
As the game trusts the players too much and (in most cases) doesn't check anything this might be a compatibility issue with another mod the Host had installed.

Do you know any other mod the Host had installed / Can you also only replicate it when joining a lobby (as opposed to when Hosting a Lobby).

**Comment by TheDeadSnake** [comment]
Closed due to no further information.
