### ISSUE TITLE
[Feature] Allow players choose input method or switch LMB with RMB

### ISSUE THREAD

**Issue by xllifi** [TheDeadSnake/LC-Touchscreen#2]
When talking to teammates via walkie I press LMB and can accidentaly activate radar booster. Is there a config?

**Comment by TheDeadSnake** [comment]
No, currently the mod uses the default player action for Interact and Use.
I'll add a solution for it in v1.0.3

**Comment by TheDeadSnake** [comment]
After updating to v1.0.3, you can modify your keybinds freely inside the "<ThunderStoreFolder>\DataFolder\LethalCompany\profiles\\<Profile\>\BepInEx\config\me.pm.TheDeadSnake.cfg"

**Comment by xllifi** [comment]
actually realised this doesn't really make sense since you have to pixel-hunt the radar to activate it
