### ISSUE TITLE
[Compatibility Request] LCVR

### ISSUE THREAD

**Issue by AlexUnknown37** [TheDeadSnake/LC-Touchscreen#20]
They don't work together, VR Player can't press the buttons. Would be an amazing mod for VR so we don't have to use the virtual keyboard.

**Comment by TheDeadSnake** [comment]
I'll try to look into it, however I will first have to get my VR setup up and running again in order to properly test it.

**Comment by NickHam13** [comment]
Any update on this?

**Comment by TheDeadSnake** [comment]
I still want to add a fix for the issue, however since I switched to Linux and my old Rift CV1 is not fully supported it will take longer than originally anticipated (until I have some more time to setup dual boot for Windows).

**Comment by NickHam13** [comment]
I understand, thanks for the reply

**Comment by TheDeadSnake** [comment]
__Update on the issue:__
The VR implementation is almost finished, the only remaining issues are: 
~~1) Controller ray has no texture/shader~~ 
~~2) Tooltips do not show up in-game~~

**Comment by TheDeadSnake** [comment]
Implemented in v1.1.1.
Release is due once the other issue is also implemented.
