### ISSUE TITLE
[Option Request] Make touchscreen cost money as an upgrade

### ISSUE THREAD

**Issue by magesnmiceys** [TheDeadSnake/LC-Touchscreen#22]
As it stands, I feel like this is super powerful but _really_ cool at the same time.  I think it'd be neat to have an option for this to be a purchasable upgrade at the terminal - I was thinking 500 credits might be a good spot for it to be, or maybe the same as inverse teleporter?

**Comment by TheDeadSnake** [comment]
Duplicate of #3.

There is a variable to enable/disable the plugin in the main class, so others may choose to create a plugin to add it to the shop.
However, I want the plugin to be as simple and straightforward as possible and do not want to add any other dependency besides BepInEx which is necessary.
