### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by DownloadsDownloads** [TheDeadSnake/LC-Touchscreen#26]
I would like some help with an issue Ive had with this mod. I have everything that it requires downloaded, but it doesn't seem to work. I have the BepInExPack already downloaded and I have the Touchscreen mod downloaded, but when I go into the terminal and type in "store" nothing seems to be listed for me to buy the touchscreen add on. I am playing with a bunch of friends (my friend is hosting, not me) and I'm curious if all the other mods make it not work, but I wouldn't see why that is. could I get some help?

**Comment by TheDeadSnake** [comment]
You do not need to buy anything in-game in oder for the mod to work.
If you installed the mod correctly and it's showing up in console during start-up you most likely have another mod installed that used the API to disable it.
In order to find out which mod disabled it, you can search your log files for the console message "Touchscreen was disabled by ".

**Comment by DownloadsDownloads** [comment]
Oooh ok, in the description for the mod it said "Upgrade your ship monitor" so I immediately thought of the ship upgrades that are buyable. also, I've even tried to make a completely separate modpack for this mod. The only mods I downloaded were the touchscreen mod that you made, and the BepInExPack. Nothing else was downloaded, no API's, only those two mods. I started the game by clicking the button that said "modded" and I watched the console start up. Everything seemed to be fine, everything was successfully loaded, but when I went into my own solo run to test it with a radar booster by putting the radar booster near a secure door and going back to the ship, there was no cursor, no prompts, just the normal UI. also, both mods have been updated to their current version. I'd be happy to answer any further questions you have to help me. I also don't understand how to set the keybinds for the quick switch function, how would I go about that?

![image_2024-03-22_211705519](https://github.com/TheDeadSnake/LC-Touchscreen/assets/97133362/5f495d0a-f54a-468c-ad33-ae2c190d2fa2)

**Comment by DownloadsDownloads** [comment]
Wait I figured it out! I was looking in the terminal where you type in commands and expecting the cursor to be there, but I didn't realize it was on the monitor that you can just look at! Nevermind LOL

**Comment by TheDeadSnake** [comment]
^^
So I guess the issue can be closed now ?

Also as for the keybinds, you have two options:
 # 1) Manually:
 > - Open the configuaration file either with a text editor or use the UI provided by Thunderstore / r2modman.
 > - Then look for the "[Layout]" line in the editor or Layout header in the UI.
 > - Change everything to suit your needs and that's it save the file / press Save in the UI and you can start up the game.
 
 # 2) In-Game:
 > - Install the mod [InputUtils](https://thunderstore.io/c/lethal-company/p/Rune580/LethalCompany_InputUtils/)
 > - Now you can configure your Keybinds in the In-Game menu.

**Comment by DownloadsDownloads** [comment]
Thank you so much! this is a great mod and I'm so happy I can use it to it's full extent now!
