### ISSUE TITLE
[Enhancement] Add default icons to dll

### ISSUE THREAD

**Issue by Dark-433** [TheDeadSnake/LC-Touchscreen#27]
SNAKE
THIS ONE THING GAVE ME A MINOR INCONVEINIENCE AND I HATE IT

YOU FORGOT TO INCLUDE THE "TheDeadSnake-Touchscreen" FILE THAT CONTAINS THE ICONS AND MAKES THEM ACTUALLY FUCKING WORK AAAAAAAAAAAAAAAAAAAAAAAAAA

i created a github account SPECIFICALLY for this ONE FUCKING THING.

**Comment by TheDeadSnake** [comment]
If you installed the most recent version v1.1.0 there should be no issue if the mod was correctly installed.
Thunderstore / r2modman takes care of it on it's own, if you however install it manually you need to call the mod folder "TheDeadSnake-Touchscreen" but this is something outside of my controll.
See #5, #9, [Wiki](https://github.com/TheDeadSnake/LC-Touchscreen/wiki/Known-issues)

**Comment by Paimon-Kawaii** [comment]
> If you installed the most recent version v1.1.0 there should be no issue if the mod was correctly installed. Thunderstore / r2modman takes care of it on it's own, if you however install it manually you need to call the mod folder "TheDeadSnake-Touchscreen" but this is something outside of my controll. See #5, #9, [Wiki](https://github.com/TheDeadSnake/LC-Touchscreen/wiki/Known-issues) 

There is another way to add crosshair icon.  
Add the crosshair picture to the project and make it become a "ManifestResource".  
Then see the code I write [here](https://github.com/Paimon-Kawaii/MonitorEnhance/blob/master/Utils/ConfigUtil.cs#L204).
This could add icon to dll and display the default crosshair icon.

**Comment by TheDeadSnake** [comment]
> There is another way to add crosshair icon. Add the crosshair picture to the project and make it become a "ManifestResource". Then see the code I write [here].(https://github.com/Paimon-Kawaii/MonitorEnhance/blob/master/Utils/ConfigUtil.cs#L204) This could add icon to dll and display the default crosshair icon.

But that would hinder players from using their own icons i.e. see the currently open pull request.

**Comment by Paimon-Kawaii** [comment]
> > There is another way to add crosshair icon. Add the crosshair picture to the project and make it become a "ManifestResource". Then see the code I write [here].(https://github.com/Paimon-Kawaii/MonitorEnhance/blob/master/Utils/ConfigUtil.cs#L204) This could add icon to dll and display the default crosshair icon.
> 
> But that would hinder players from using their own icons i.e. see the currently open pull request.

These are not conflict.  
If player wants to use custom icons, just type the available paths in the config, otherwise the mod will use default icons.

**Comment by TheDeadSnake** [comment]
Added images to the .dll file in v1.1.1
