### ISSUE TITLE
[Compatibility] ToilHead

### ISSUE THREAD

**Issue by JohnMetroid** [TheDeadSnake/LC-Touchscreen#29]
Hey there,

We've been using the touchscreen mod for a long time now and it's an amazing upgrade to the ship.  But as far as we can tell, the touchscreen doesn't allow interaction with manti-toils, etc... Is this something that can be investigated and potentially implemented into touchscreen?

Thanks for the consideration

![image](https://github.com/user-attachments/assets/ce1cb706-8602-430c-a7d0-9ac3f8188bc1)

**Comment by TheDeadSnake** [comment]
Added in v1.1.3
