### ISSUE TITLE
[Suggestion] Config option as a terminal bought upgrade?

### ISSUE THREAD

**Issue by SonicX8000** [TheDeadSnake/LC-Touchscreen#3]
I wonder if this could be a terminal bought upgrade to make the monitor have the touchscreen ability. Just for some kind of balance seeing that you can just touch doors/turrets/mines to disable/ope/close them.

**Comment by TheDeadSnake** [comment]
I can look into it but the mod itself does nothing you can not do using the Terminal and a simple script / macro to achieve the same actions / speed.
If I implement it, I will add a config option to toggle it and have it off by default.

**Comment by TheDeadSnake** [comment]
After thinking about it and working on it, I ultimately scrapped it and decided to not implement the feature as it does not fit the scope of the plugin.

I have however added a possibility for other plugins to enable/disable the feature so they may integrate it if they so desire.
```c#
touchscreen.Plugin.IsActive = <true/false>
```
