### ISSUE TITLE
Gamepad issues

### ISSUE THREAD

**Issue by notfatchicks44** [TheDeadSnake/LC-Touchscreen#30]
Hello! Mod works great but unfortunately, I cannot to seem to get the screen to work with gamepad or with users on the steam deck, the buttons appear as question marks, is it possible to get it working for both keyboard users and gamepad users in the same lobby? if so how would I format the keybinds in the config? Thanks!

**Comment by TheDeadSnake** [comment]
The mod is completely client-side, so it does not matter if you are in a online lobby or play offline.

If you want to use a Controller you'll need to either:
 1) Edit the config file
     - Use a editor to edit file* itself
     - Use the integrated editor in the Thunderstore / r2modman application.
 2) Or install the mod [InputUtils](https://thunderstore.io/c/lethal-company/p/Rune580/LethalCompany_InputUtils/) and change them in the in-game settings.

Lastly the keybindings should only be question marks if the entered binding is invalid.

*) The config "me.pm.TheDeadSnake.cfg" is located inside your "BepInEx/config/" folder.

If you think you did everything and it still does not work, please post the relevant config sections and if possible console output of the mods startup and I will mark this issue as a bug and try to look into it.

**Comment by notfatchicks44** [comment]
Hello! I appreciate the fast reply! I do apologize in advance as I am new to modding, it seems with the InputUtils i can correctly configure the "x" button to interact and the "right trigger" to flash, how would i go about correctly setting that up manually in the config? i can see how to type them but i cant seem to get the buttons formatted correctly/get the name of the buttons right, would appreciate it very much as my friends play on steam deck and its hard for them to manually edit the configs, thanks!

**Comment by TheDeadSnake** [comment]
If you want to edit the file manually, you'll first need to locate it in the above mentioned location.
Then:
 1) Search under `[Layout]` for the relevant sections for the "Primary" and "Secondary" keybinds (Roughly at line 28 and 36)
 2) As the keybinds are generalized (XBox, PS, Steam Deck, ...) by Unity you can not use e.g. "\<GamePad\>/X". Instead you can use:
  -  The right buttons on the controller `<Gamepad>/buttonNorth` same format for East, South and West
  - And for the trigger / shoulder buttons use `<Gamepad>/leftShoulder`, `<Gamepad>/leftTrigger` (same format for right).
(See: [GetButtonDescription](https://github.com/TheDeadSnake/LC-Touchscreen/blob/5c9bfaf8f06cc3c058435b73c286d37038da7234/util/InputUtil.cs#L67) for other common key-bindings).

The keybinding you most likely want would be:
 * Primary: `<Gamepad>/buttonSouth`
 * Secondary: `<Gamepad>/rightTrigger`

**Comment by notfatchicks44** [comment]
Thank you! Worked like a charm :)
