### ISSUE TITLE
Disappearing Cursor | Issue with "High Quota Fixes" 

### ISSUE THREAD

**Issue by Angrymanaboutcomp** [TheDeadSnake/LC-Touchscreen#31]
When I look at the monitor the cursor appears but right after it dissapears

**Comment by TheDeadSnake** [comment]
This sounds like an compatibility issue with another mod; If you only use a few mods could you provide a list of them so I can take a look at it ?

**Comment by Angrymanaboutcomp** [comment]
-LoadstoneNightly
-LethalConfig
-ButteryFixes
-EnemySoundFixes
-MeleeFixes
-WeedKillerFixes
-High_Quota_Fixes
-NoJumpDelay
-LethalFixes
-LethalPerformance
-VanillaMoonsLagFix
-FixPluginTypesSerialization
-HookGenPatcher
-LC_FastStartup
-CullFactory
-Boombox_Sync_Fix
-LCMaxSoundsFix
-InteractiveTerminalAPI
-ReverbTriggerFix
-VertexLibrary
-FixCentipideLag
-AsyncLoggers
-LobbyControl
-Matty_Fixes_Experimental
-MMHOOK
-ApparatusFix
-LightsOut
-HDLethalCompany
-PerformanceEnhancer
-GoodItemScan
-Touchscreen
-PathfindingLagFix
-AlwaysHearWalkie
-Fix Camera Resolution

**Comment by TheDeadSnake** [comment]
Tested your mod selection and found out that this is an issue with the [High Quota Fixes](https://thunderstore.io/c/lethal-company/p/Chboo1/High_Quota_Fixes/) mod.

In order to fix the "disappearing cursor" issue disable the `EnableInteractFix` in the `[General.Toggles]` config section.
