### ISSUE TITLE
Incompatibility with Fire Exit Flip

### ISSUE THREAD

**Issue by Kevin-from-HP** [TheDeadSnake/LC-Touchscreen#32]
Hey. I love this mod, but currently it stops Fire Exit Flip from working for some reason sadly

**Comment by TheDeadSnake** [comment]
I'm unable to reproduce the issue, both mods work as expected.

Are you sure it's the combination of Touchscreen and FireExitFlip and not some other mod(s) ?
After looking at the de-compiled source code of the FireExitFlip plugin, they do not overlap anywhere. So it should be impossible for either mod to break the other.

## Mods used:
**Name**: FireExitFlip
**Author**: PC
**Version**: 1.0.0
**URL**: [Link](https://thunderstore.io/c/lethal-company/p/PC/FireExitFlip/)

**Name**: Touchscreen
**Version**: 1.1.3
**URL**: [Link](https://thunderstore.io/c/lethal-company/p/TheDeadSnake/Touchscreen/)

**Comment by Kevin-from-HP** [comment]
Did a very basic binary search to find the conflict, disabling yours fixed the issue but didn't try only the 2 mods together, which is a lapse in my part.
Will investigate further and get back to you

EDIT: Trying only both mods together causes no conflicts so I'm either going crazy and made a mistake doing the search,
OR it's a combination of multiple mods shenanigans that caused it and turning off yours fixed it for some god forsaken reason.

Whatever it is it is fixed and i sincerely apologise for wasting your time

**Comment by TheDeadSnake** [comment]
No problem ^^
Have fun playing :D
