### ISSUE TITLE
[Suggestion] reticle as cursor image option(s)

### ISSUE THREAD

**Issue by lifegrain** [TheDeadSnake/LC-Touchscreen#4]
I'm not sure if the "point" of the cursor image is where I am aiming, an alternative cursor image option for a reticle instead would be nice perhaps a simple dot, square, or cross as I believe it would clearly show where a player is aiming

especially useful for when 2 trigger-able objects are near to each other, i.e: door and turret

the main culprit is from the base game's "hand" cursor image that seem to "point" to where a player expect to interact but it's actually the center of the "hand" cursor image, most noticeable when flipping the switches in a circuit box / breaker and the switch player and turn off/on button on the main monitor in the ship

just thought it would be a nice addition to avoid minor confusion

**Comment by TheDeadSnake** [comment]
The monitor pointer is pointing to the 'precise' screen center, but I get what you mean with the default icons.
However as the used icon image is just inside the plugins folder* it can be replaced by the user if wanted with anything else. I can add another version to the plugin, but the user would still need to change either the image name or a config variable to exchange them.
Lastly, unless there is a larger demand I do not plan to add a custom settings GUI for the plugin as I want to keep the plugin plug n' play as much as possible.

*Icon path: "\<ThunderStoreFolder\>\DataFolder\LethalCompany\profiles\\<Profile\>\BepInEx\plugins\TheDeadSnake-Touchscreen\HoverIcon.png"

**Comment by TheDeadSnake** [comment]
Added in commit 42284f6348049a98d84334f025dc6bd290dfbd08 will be added to the plugin when 1.0.4 releases.
Release date is not known yet but should be (max.) within the next 48hrs.
