### ISSUE TITLE
[Duplicate] Cursor issue

### ISSUE THREAD

**Issue by SANDMAN343** [TheDeadSnake/LC-Touchscreen#6]
For some reason the cursor is replaced for a big square
Try a clean install (only BepInEx and the mod) but still not working

**Comment by TheDeadSnake** [comment]
To make sure the mod works as intended, use at least version 1.0.1 of the mod and install it automatically using Thunderstore Mod Manager.

If you want to install it manually make sure you name the plugin folder "TheDeadSnake-Touchscreen" and place it inside the BepInEx plugins folder.

If you followed all these steps and it still does not work, try the steps from #1 as well.

P.S.: When the plugin is enabled and the cursor image could not be found it will also print the path to console, where it expected the image to be. e.g.:
```
[Info   :   BepInEx] Loading [TouchScreen 1.0.4]
[Warning:TouchScreen]  > Unable to locate hover icon at path: \<Path\>\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\\<Profile\>\BepInEx\plugins\TheDeadSnake-Touchscreen\HoverIcon.png
[Info   :TouchScreen] Enabled TouchScreen
```

**Comment by TheDeadSnake** [comment]
If after all these steps the icon is still not loading in, please add another comment.

**Comment by SANDMAN343** [comment]
Change the folder name inside plugins fix the issue
thank you!
5/5 mod
