### ISSUE TITLE
[Suggestion] Key bind to switch radar

### ISSUE THREAD

**Issue by counttec** [TheDeadSnake/LC-Touchscreen#7]
Would it be possible to add a key bind, like "Q" to perform the standard action of cycling the feed to the next person?

**Comment by TheDeadSnake** [comment]
I do not think that this is a key bind that many would need. I mean the button is right on the monitor and would take away an extra keybind that might make mod compatibility harder (For bigger mod packs).
However as it's a QoL improvement and still somewhat fits the mod, I will add it as a optional keybind so you may use it if you want to.

**Comment by TheDeadSnake** [comment]
Added in a845f74696de3037e4f29ca363e58462682fb0b0.
